server.port: 8081

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: {POSTGRES_USER}
    password: {POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 5
      idle-timeout: 600000
  liquibase:
    change-log: classpath:/liquibase/changelog.yaml
    drop-first: true