kind: Service
apiVersion: v1
metadata:
  name: springhello
  labels:
    name: springhello
spec:
  ports:
    - nodePort: 30163
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: springhello
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springhello
spec:
  selector:
    matchLabels:
      app: springhello
  replicas: 3
  template:
    metadata:
      labels:
        app: springhello
    spec:
      containers:
        - name: springhello
          image: gondri009/springhello:springhello
          ports:
            - containerPort: 8081
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password